version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: clinical_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: supersecurepassword
      POSTGRES_DB: clinical_os
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    container_name: clinical_qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped

  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: clinical_timescale
    environment:
      POSTGRES_PASSWORD: telemetrypassword
    ports:
      - "5433:5432" # 5433 so it doesn't clash with normal Postgres
    volumes:
      - timescale_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: clinical_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: clinical_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://admin:supersecurepassword@postgres:5432/clinical_os
      - REDIS_URL=redis://redis:6379/0
      - QDRANT_URL=http://qdrant:6333
    depends_on:
      - postgres
      - qdrant
      - redis
      - timescaledb
    volumes:
      - ./backend:/app
    restart: unless-stopped

volumes:
  postgres_data:
  qdrant_data:
  timescale_data: